### PR TITLE
turn cursor and illegal move bug fixes

### LINKED ISSUE #4: Illegal move error firing when it shouldn't
The illegal move check fires inappropriately during a game because it's based on player card ownership totals being used to determine how many turns a player has taken. This is a problem because ownership can change a lot in a single turn, resulting in misleading totals.

This can be fixed by updating the board cell values to include the original card player and checking those values instead.

### LINKED ISSUE #5: Duplicate card error firing inappropriately
The duplicate card check is meant to ensure players aren't trying to submit a play containing duplicate cards. This is an issue because if player one plays card A, player 2 uses a different card to flip card A (now owning it), then tries to play their own card A, it will be counted as an illegal move.

This check can be removed since the server will validate these plays, or the check can be expanded to check if the player trying to play the card is the original player of the card currently on the board.

### LINKED ISSUE #6: Update cell string format
Let's make the cell string more detailed by including labels. For example:

`player:one|owner:one|card:cardName`

### PR DESCRIPTION
**Pull request by klassenjo**
added floating turn indicating cursor, removed duplicate card check from playCard

### CODE REVIEW

File: packages/frontend-react/src/components/Hand/Hand.tsx [hunk 1]
```diff
@@ -43,19 +49,31 @@ export const Hand = ({ player, active = false, onCardSelected }: HandProps) => {
...
+
+      {/* Score */}
+      <span
+        className={clsx('m-auto', styles.score)}
+        data-direction={
+          player.label == TripleTriad.Player.One ? 'left' : 'right'
+        }
+      >
+        {score}
+      </span>
```
Comment (jakeklassen) [inline packages/frontend-react/src/components/Hand/Hand.tsx]: Turn these into actual named components instead of comments. E.g. `<Score />`

File: packages/game/src/lib/find-duplicate-player-card.ts [hunk 2]
```diff
@@ -5,9 +5,10 @@ import { PlayerLabel } from './player';
 export const findDuplicatePlayerCard = (
   board: ReadonlyDeep<Board>,
   playerLabel: PlayerLabel,
+  ownerLabel: PlayerLabel,
```
Comment (jakeklassen) [inline packages/game/src/lib/find-duplicate-player-card.ts]: Let's skip passing the owner altogether. We had everthing we needed before, but now we'll expand the `flatMap` to pull the string apart and compare `card` and `player` of the card.

File: packages/game/src/lib/who-played-card.test.ts [hunk 3]
```diff
@@ -0,0 +1,42 @@
+import { describe, expect, it } from 'vitest';
+import { Board, Position } from './common-types';
+import { whoPlayedCard } from './who-played-card';
+
+describe('whoPlayedCard', () => {
+  const cases = [
+    [
+      'one',
+      [0, 0] as Position,
```
Comment (jakeklassen) [inline packages/game/src/lib/who-played-card.test.ts:9]: Looks like we cast to `Position` often enough that we could write a `position` function that takes `x` and `y` and returns a `Position`. Called like `position(0, 0)` instead.

File: packages/game/src/lib/sum-player-turns.ts [hunk 4]
```diff
@@ -5,12 +5,12 @@ import { Player } from './player';
 export const sumPlayerTurns = (board: ReadonlyDeep<Board>) => {
   const flat = board.flat();
 
-  const playerOneMoveCount = flat.filter((cell) =>
-    cell?.includes(Player.One),
+  const playerOneMoveCount = flat.filter(
+    (cell) => cell?.split(':')[0] === Player.One,
```
Comment (jakeklassen) [inline packages/game/src/lib/sum-player-turns.ts]: This could be `cell?.startsWith(Player.One)` and keep it simple.

File: packages/game/src/lib/is-board-empty.test.ts [hunk 5]
```diff
@@ -15,9 +15,9 @@ describe('isBoardEmpty', () => {
 
   it('should return false if any cell is not null or undefined', () => {
     const board: Board = [
-      ['one:red bat', 'one:fungar', 'one:geezard'],
-      ['one:red bat', 'one:fungar', 'one:geezard'],
-      ['one:red bat', 'one:fungar', undefined],
+      ['one:one:red bat', 'one:one:fungar', 'one:one:geezard'],
+      ['one:one:red bat', 'one:one:fungar', 'one:one:geezard'],
+      ['one:one:red bat', 'one:one:fungar', undefined],
```
Comment (jakeklassen) [inline packages/game/src/lib/is-board-empty.test.ts]: Could we use the `createBoardFromHand` helper here to simplify.

Comment (jakeklassen) [reply packages/game/src/lib/is-board-empty.test.ts]: Updated helper to take a Hand instead of a Card[], updated calls where necessary.

**Review by jakeklassen — APPROVED** [review]
